name: MR Testing

on:
  push:
    branches-ignore:
      - master

env:
  UNITY_LICENSE: ${{ secrets.UNITY_LICENSE_FILE }}

jobs:
  checkLicense:
    name: Check Unity License
    runs-on: ubuntu-latest
    steps:
      - name: Fail - No License
        if: ${{ !startsWith(env.UNITY_LICENSE, '<')}}
        run: exit 1

  testRunner:
    needs: checkLicense
    name: ${{ matrix.testMode }} Tests
    runs-on: ubuntu-latest-16-cores
    strategy:
      fail-fast: false
      matrix:
        testMode:
          - EditMode
          - PlayMode
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Create LFS file list
        run: git lfs ls-files -l | cut -d' ' -f1 | sort > .lfs-assets-id

      - name: Restore LFS cache
        uses: actions/cache@v2
        id: lfs-cache
        with:
          path: .git/lfs
          key: ${{ runner.os }}-lfs-${{ hashFiles('.lfs-assets-id') }}

      - name: Git LFS Pull
        run: |
          git lfs pull
          git add .
          git reset --hard

      - name: Restore Library cache
        uses: actions/cache@v2
        with:
          path: Library
          key: Library-test-project-${{ matrix.targetPlatform }}
          restore-keys: |
            Library-test-project-
            Library-

      - name: Run tests
        uses: game-ci/unity-test-runner@v2
        id: testRunner
        with:
          testMode: ${{ matrix.testMode }}
          checkName: ${{ matrix.testMode }} test results
          githubToken: ${{ secrets.GITHUB_TOKEN }}
          gitPrivateToken: ${{ secrets.API_ACCESS_PAT }}

      - uses: actions/upload-artifact@v2
        with:
          name: Test results (${{ matrix.testMode }})
          path: ${{ steps.testRunner.outputs.artifactsPath }}